---
generic_packages:
  - curl
  - acpid
  - bash-completion
  - bzip2
  - coreutils
  - dmidecode
  - dos2unix
  - dstat
  - e2fsprogs
  - elinks
  - groff
  - htop
  - jq
  - inotify-tools
  - irqbalance
  - logrotate
  - ltrace
  - lvm2
  - lynx
  - ncdu
  - ngrep
  - nmap
  - ntp
  - ntpdate
  - man
  - mlocate
  - mr
  - mtr
  - multitail
  - openssh-server
  - openvpn
  - parted
  - pciutils
  - perl
  - policycoreutils
  - pv
  - rcs
  - rkhunter
  - rng-tools
  - rsync
  - screen
  - shellcheck
  - sshuttle
  - sudo
  - sssd
  - sssd-tools
  - sssd-common
  - sysstat
  - strace
  - tar
  - tcl
  - terminator
  - tk
  - tree
  - unzip
  - wget
  - whois
  - vim-common
  - vmtouch
  - zip

redhat_packages:
  - dhclient
  - iputils
  - kernel-headers
  - man-pages
  - nc
  - openssh
  - openssh-server
  - openssl-devel
  - python
  - python-pip
  - python-httplib2
  - redhat-lsb
  - setransd
  - tmpwatch
  - tuned
  - which
  - vim-enhanced
  - yum-plugin-changelog
  - yum-plugin-downloadonly
  - yum-plugin-ps
  - yum-utils
  - zlib-devel

redhat_packages_6:
  - pam_passwdqc

redhat_packages_conflicting_remove:
  - nfs-utils

debian_packages:
  - apparmor-profiles
  - apparmor-utils
  - iwatch
  - iptables-persistent
  - bind9utils
  - pinentry-gtk2
  - kernel-package
  - libreadline-dev
  - netcat
  - openssh-client
  - python3
  - python3-pip
  - python3-httplib2
  - systemd-container
  - ubuntu-restricted-extras
  - vim-scripts
  - virtualenv
  - zlib1g-dev
  - libykclient3
  - libykpers-1-1
  - pcsc-tools
  - opensc
  - opensc-pkcs11
  - libccid
  - pcscd
  - yubioath-desktop
  - yubikey-personalization-gui
  - yubikey-luks
  - yubikey-ksm
  - yubico-piv-tool
  - ykneomgr
  - libpam-yubico
  - scdaemon
  - gnupg-pkcs11-scd
  - strace

debian_packages_gui:
  - metacity-themes
  - ubuntu-gnome-desktop

rk_email: root

missing:
  - nivada-current
