---
os_packages:
  - bind-utils
  - dhclient
  - iputils
  - kernel-headers
  - man-pages
  - nc
  - openssh
  - openssh-server
  - openssl-devel
  - pcsc-lite
  - pcsc-tools
  - python
  - python-pip
  - python-httplib2
  - redhat-lsb
  - setransd
  - tmpwatch
  - tuned
  - which
  - whois
  - vim-enhanced
  - yum-plugin-changelog
  - yum-plugin-downloadonly
  - yum-plugin-ps
  - yum-utils
  - zlib-devel

os_packages_conflicting_remove:
  - nfs-utils

os_packages_gui:


os_banned_packages:
