---
- hosts: localhost
  gather_facts: yes
  vars_files:
    - vars.yml
  roles:
    - { role: generic }
    - { role: fstab }
    - { role: os-hardening,
        os_desktop_enable: true,
        os_security_packages_list: ['xinetd','inetd','ypserv','telnet-server','rsh-server'] }
    - { role: ssh-hardening }
    - { role: iptables }
    - { role: grub-cmdline }
    - { role: audit-hardening }
    - { role: docker }
    - { role: minikube }
#    - { role: kubectl }
#    - { role: docker_images }
#    - { role: toolbox }
    - { role: virtualbox }
    - { role: vagrant }
    - { role: packer }
    - { role: slack }
    - { role: clamav }
